version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: "always"
    volumes:
      - ./.dbcache/mongo/data:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend
  api:
    image: node:12.16.3-alpine
    container_name: "nodejs"
    ports:
      - "3333:3333"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "npm install"
    command: "npm start"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"